/*
 * Project Name: Temperature Control App
 * Author: Taylor Lee
 * Last modified: September 30th, 2022
 * Desc: You will build a temperature control app where users can increment/decrement temperature and the
 * background color changes based on temperature.
*/


//This was generated by npx and wasn't changed by the author.
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

